### ISSUE TITLE
GoHive Kerberos fatal error: gssapi/gssapi.h: No such file or directory on Windows

### ISSUE THREAD

**Issue by KaluTheKova** [beltran/gohive#101]
Hello again!

I'm trying to use GoHive with Kerberos. Unfortunately, there seems to be no libkrb5-dev for Windows 10.
I do have MIT Kerberos with SDK and TDM64-GCC installed. 
The file gssapi.h is located in C:\Program Files\MIT\Kerberos\include\gssapi.
I have env variable MITKRB5 pointing to C:\Program Files\MIT\Kerberos\

But I still get the following erros when I try to run:

```
go get -tags kerberos github.com/beltran/gohive

..\..\pkg\mod\github.com\beltran\gssapi@v0.0.0-20200324152954-d86554db4bab\buffer.go:9:10: fatal error: gssapi/gssapi.h: No such file or directory
    9 | #include <gssapi/gssapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

go get -tags kerberos github.com/beltran/gosasl

# github.com/beltran/gssapi
..\..\pkg\mod\github.com\beltran\gssapi@v0.0.0-20200324152954-d86554db4bab\buffer.go:9:10: fatal error: gssapi/gssapi.h: No such file or directory
    9 | #include <gssapi/gssapi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by beltran** [comment]
Hello, I haven't tried kerberos in windows but I'm not sure it will work. Unfortunately as far as I know there's not an easy way to do this. It may be possible to use a windows compiler to this like it's described in the node mongodb driver: http://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/, but this looks far from easy.

**Comment by KaluTheKova** [comment]
Okay, that sounds nasty. Guess I'll have to try tweaking or a different OS. Thank you. I'll let you know if can get it working on Windows and the instructions how to do it.

**Comment by KaluTheKova** [comment]
After trying a few things, I'd say the best way is to just build the binary in a container that has required libraries.

However, I'm unable to build it in debian buster or Linux. I'll open a new issue for that.
