### ISSUE TITLE
HiveConfiguration

### ISSUE THREAD

**Issue by hugepizza** [beltran/gohive#103]
I create a connect with HiveConfiguration.
`conf.HiveConfiguration = map[string]string{"tez.queue.name": yarnQueue}`
But queries with the connect can not submit to the correct queue,sometimes they are correct sometimes wrong.

**Comment by beltran** [comment]
hmm I'm not sure why that would happen, the driver doesn't reconnect or similar, it just connects once. Are you sure the property is not set? Maybe it's set and it's not a driver issue. You could verify the value of the variable with:
`cursor.Exec(context.Background(), "SET tez.queue.name")`
and you could set it manually with:
`cursor.Exec(context.Background(), "SET tez.queue.name = yarnQueue")`

**Comment by beltran** [comment]
Closing as obsolete, let me know if you're still running into this.
