### ISSUE TITLE
Add cursor.FetchOne with interface value support

### ISSUE THREAD

**Issue by MinhVuLe225** [beltran/gohive#106]
I was running something like this:
```
i:=make([]interface{},100)
for cursor.HasMore(ctx) {
	cursor.FetchOne(ctx,i...)
	if cursor.Err != nil {
		log.Fatal(cursor.Err)
	}
}
```
and the return was:
```
Unexpected data type <nil> for value 2019 (should be string)
```
Can you please add support for the interface{} type?
Thank you very much ^^

**Comment by beltran** [comment]
Hello, I think this would be useful, in the meantime you could use [RowMap](https://github.com/beltran/gohive/blob/65689e5f121c86156d2790cb6fbbab6d08279aad/hive.go#L553) if you don't want to define all the variables
