### ISSUE TITLE
 Issue with setup : go get github.com/beltran/gohive

### ISSUE THREAD

**Issue by selmi2** [beltran/gohive#113]
It returns this error 
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1044:36: not enough arguments in call to iprot.ReadStructBegin
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1049:55: not enough arguments in call to iprot.ReadFieldBegin
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1063:25: not enough arguments in call to iprot.Skip
        have (thrift.TType)
        want (context.Context, thrift.TType)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1082:31: not enough arguments in call to iprot.ReadFieldEnd
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1086:31: not enough arguments in call to iprot.ReadStructEnd
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1093:28: not enough arguments in call to iprot.ReadI32
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1102:31: not enough arguments in call to iprot.ReadString
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1114:34: not enough arguments in call to oprot.WriteStructBegin
        have (string)
        want (context.Context, string)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1125:32: not enough arguments in call to oprot.WriteFieldStop
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1128:32: not enough arguments in call to oprot.WriteStructEnd
        have ()
        want (context.Context)
go/src/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1128:32: too many errors

**Comment by beltran** [comment]
This is happening because you are not compiling against [thrift 0.12](https://github.com/beltran/gohive/blob/master/go.mod#L6). There must be a thrift package with a higher version around.

**Comment by selmi2** [comment]
Thanks. I will check.

**Comment by selmi2** [comment]
Same error. I verified correct modules versions installed:
go: downloading github.com/beltran/gosasl v0.0.0-20200715011608-d5475aebb293
go: downloading github.com/go-zookeeper/zk v1.0.1
go: downloading github.com/apache/thrift v0.12.0
go: extracting github.com/beltran/gosasl v0.0.0-20200715011608-d5475aebb293
go: extracting github.com/go-zookeeper/zk v1.0.1
go: extracting github.com/apache/thrift v0.12.0
go: finding github.com/beltran/gosasl v0.0.0-20200715011608-d5475aebb293
go: finding github.com/apache/thrift v0.12.0
go: finding github.com/go-zookeeper/zk v1.0.1

**Comment by selmi2** [comment]
Wrong thrift version was installed. Thanks.
