### ISSUE TITLE
Possible to connect in embedded mode?

### ISSUE THREAD

**Issue by WhileLoop** [beltran/gohive#114]
Is it possible to connect to Hive running in embedded mode (connection string `jdbc:hive2://`) with this package?

**Comment by beltran** [comment]
The embedded mode defined [here](https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.3.4.7/bk_dataintegration/content/hive-jdbc-odbc-drivers.html) so that gohive would start itself a HiveServer2? Unfortunately no, gohive needs a running hive to connect to.

**Comment by WhileLoop** [comment]
I didn't realize that's what it was doing. Thanks.
