### ISSUE TITLE
Runtime bug or uncaught exception, in example/main.go

### ISSUE THREAD

**Issue by advancedwebdeveloper** [beltran/gohive#117]
Hi.

I just compiled your example, via

> $go build

.

Then I tried to launch the executable:
>  ./example
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x442d6c]
> 
> goroutine 1 [running]:
> github.x2ecom..z2fapache..z2fthrift..z2flib..z2fgo..z2fthrift.TSocket.IsOpen
> 	/home/oceanfish81/go_projects/gohive/vendor/github.com/apache/thrift/lib/go/thrift/socket.go:111
> github.x2ecom..z2fapache..z2fthrift..z2flib..z2fgo..z2fthrift.TSocket.Open
> 	/home/oceanfish81/go_projects/gohive/vendor/github.com/apache/thrift/lib/go/thrift/socket.go:85
> gohive.innerConnect
> 	/home/oceanfish81/go_projects/gohive/hive.go:166
> github.x2ecom..z2fbeltran..z2fgohive.Connect
> 	/home/oceanfish81/go_projects/gohive/hive.go:119
> main.main
> 	/home/oceanfish81/go_projects/gohive/example/main.go:16
> 

. If there is an uncaught exception - it is just hard to distinguish misconfigured external resources (no open port, for the socket) from something else.

**Comment by advancedwebdeveloper** [comment]
This could be of help:

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/go_projects/gohive/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build195660082=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by beltran** [comment]
Hello, I'm not sure if `go build && ./example` would run it but I guess the you're running the main.go under example (similar to `go run example/main.go`). The example relies on hive server listening on "hs2.example.com", you can tweak the example and point it to wherever your hive instance is running.

**Comment by beltran** [comment]
Closing for now, since this is expected when hive is not running at hs2.example.com
