### ISSUE TITLE
error on   go get github.com/beltran/gohive

### ISSUE THREAD

**Issue by novozale** [beltran/gohive#129]
Get error message:
# github.com/beltran/gohive/hiveserver
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1044:36: not enough arguments in call to iprot.ReadStructBegin
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1049:55: not enough arguments in call to iprot.ReadFieldBegin
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1063:25: not enough arguments in call to iprot.Skip
        have (thrift.TType)
        want (context.Context, thrift.TType)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1082:31: not enough arguments in call to iprot.ReadFieldEnd
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1086:31: not enough arguments in call to iprot.ReadStructEnd
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1093:28: not enough arguments in call to iprot.ReadI32
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1102:31: not enough arguments in call to iprot.ReadString
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1114:34: not enough arguments in call to oprot.WriteStructBegin
        have (string)
        want (context.Context, string)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1125:32: not enough arguments in call to oprot.WriteFieldStop
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1128:32: not enough arguments in call to oprot.WriteStructEnd
        have ()
        want (context.Context)
../../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1128:32: too many errors

**Comment by beltran** [comment]
This is a duplicate of https://github.com/beltran/gohive/issues/113. This is happening because you are not compiling against [thrift 0.12](https://github.com/beltran/gohive/blob/master/go.mod#L6). There must be a thrift package with a higher version around.

**Comment by novozale** [comment]
Thank you very much for quick answer, but unfortunately I can't get package without errors
I have tried to install thrift this way:
sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
and this way:
go get github.com/apache/thrift/lib/go/thrift
but result is the same:
# github.com/beltran/gohive/hiveserver
../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1044:36: not enough arguments in call to iprot.ReadStructBegin
        have ()
        want (context.Context)
../go/src/github.com/beltran/gohive/hiveserver/HiveServer.go:1049:55: not enough arguments in call to iprot.ReadFieldBegin
        have ()
        want (context.Context) ...
What I am duing wrong?

**Comment by beltran** [comment]
You probably have to enable go modules, you can do this with
`export GO111MODULE=on`

and then try
`go get github.com/beltran/gohive`

**Comment by novozale** [comment]
Jaume, Thank you for help! After "export GO111MODULE=on" everything work correct

**Comment by beltran** [comment]
Sure! Happy to help
