### ISSUE TITLE
Added support for VARCHAR type in old version

### ISSUE THREAD

**Issue by fatelei** [beltran/gohive#154]
gohive upgrade thrift version to 0.14.0，but my project require thrift version under 0.12.0，can you add this support in v1.0.1 ?

**Comment by beltran** [comment]
Hello, I've created: https://github.com/beltran/gohive/releases/tag/v1.5.0_thrift0.12, which is the current master but with thrift set to 0.12, let me know if this doesn't work for you.

**Comment by fatelei** [comment]
thank you,  i will try using this version and give you feedback

**Comment by fatelei** [comment]
this version work for me, i will close this issue, thank you very much.

**Comment by beltran** [comment]
No problem, happy to hear it worked!
