### ISSUE TITLE
responseExecute panic

### ISSUE THREAD

**Issue by fanjindong** [beltran/gohive#162]
```go
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 4793785 [running]:
git.ddxq.mobi/ddmc-engine/chain/utils.SqlHive.func1.1.1(0xc012e36800, 0x7e, 0xc5587eb4a0)
   /data1/jenkins/workspace/golang-service_2/chain/utils/sql.go:41 +0xba
panic(0x1375d40, 0x1fd2460)
   /usr/local/go1.15.2/src/runtime/panic.go:969 +0x175
github.com/beltran/gohive.(Cursor).executeAsync(0xc54e821c80, 0x1762280, 0xc0000340b0, 0xc012e36800, 0x7e)
   /var/lib/jenkins/go/pkg/mod/github.com/beltran/gohive@v1.5.1/hive.go:538 +0x26a
github.com/beltran/gohive.(Cursor).Execute(0xc54e821c80, 0x1762280, 0xc0000340b0, 0xc012e36800, 0x7e, 0x0)
   /var/lib/jenkins/go/pkg/mod/github.com/beltran/gohive@v1.5.1/hive.go:464 +0x57
git.ddxq.mobi/ddmc-engine/chain/utils.sqlHive(0x1762280, 0xc0000340b0, 0xc000208310, 0x12bd760, 0xc4d9c61040, 0xc012e36800, 0x7e, 0x0, 0x0)
   /data1/jenkins/workspace/golang-service_2/chain/utils/sql.go:116 +0x21b
git.ddxq.mobi/ddmc-engine/chain/utils.SqlHive.func1.1(0xc012e36800, 0x7e, 0xc5587eb4a0, 0x1762280, 0xc0000340b0, 0xc000208310, 0x12bd760, 0xc4d9c61040)
   /data1/jenkins/workspace/golang-service_2/chain/utils/sql.go:49 +0xc8
created by git.ddxq.mobi/ddmc-engine/chain/utils.SqlHive.func1
   /data1/jenkins/workspace/golang-service_2/chain/utils/sql.go:37 +0x171
```

`chain/utils/...` It's my own stack that you can ignore.
This exception occasionally occurs on the line.

**Comment by fanjindong** [comment]
[gohive@v1.5.1/hive.go:538](https://github.com/beltran/gohive/blob/a5e5c59c8d62dce9f50dd68bf1751209def75a79/hive.go#L538)
Maybe we need to check whether it's a null pointer

**Comment by fanjindong** [comment]
[Another possible exception](https://github.com/beltran/gohive/blob/a5e5c59c8d62dce9f50dd68bf1751209def75a79/hiveserver/HiveServer.go#L9270)
This could also cause an panic？

**Comment by beltran** [comment]
Hmm, interesting, thank you for the bug description, I think it could also be [this line](https://github.com/beltran/gohive/blob/a5e5c59c8d62dce9f50dd68bf1751209def75a79/hive.go#L530). I'll put up a fix.

**Comment by beltran** [comment]
I think that should do it, please let me know if you see this again.

**Comment by fanjindong** [comment]
@beltran 
Wait, I read your commit.
I understand 
`int(*responseExecute.Status.ErrorCode)` and 
`int(*responseExecute.GetStatus().ErrorCode)` these are equivalent.
Why was it fixed.

**Comment by fanjindong** [comment]
if `responseExecute.Status` return `nil`, 
so `responseExecute.GetStatus()` still return `nil`

**Comment by beltran** [comment]
When `responseExecute.Status` is nil,  `responseExecute.GetStatus()` returns `TExecuteStatementResp_Status_DEFAULT`. See the GetStatus() definition: https://github.com/beltran/gohive/blob/a5e5c59c8d62dce9f50dd68bf1751209def75a79/hiveserver/HiveServer.go#L9268-L9273

Note that IsStatus() returns false if `Status` is nil: https://github.com/beltran/gohive/blob/a5e5c59c8d62dce9f50dd68bf1751209def75a79/hiveserver/HiveServer.go#L9281-L9283

**Comment by fanjindong** [comment]
LGTM
