### ISSUE TITLE
How to specific session Id with HiveConfiguration?

### ISSUE THREAD

**Issue by LiShangAn** [beltran/gohive#169]
Hello,

I use apache livy to start a thirft server for spark, the hive jdbc url just like this:

                        jdbc:hive2://localhost:10090/?livy.server.sessionId=0

And the hive url is localhost:10090

Does this package support to set the query parameter?  (ex: livy.server.sessionId)

Should I set this in HiveConfiguration?

The conf.HiveConfiguration = map[string]string{"key": value}

How do I find out which keys can be set?

Thanks :)

**Comment by beltran** [comment]
Passing a custom url is not supported, the connection is constructed from the `ConnectConfiguration` parameters, see [this method](https://github.com/beltran/gohive/blob/cb0d49e69d68a27c1f16f7bd217125c799de0a43/hive.go#L185) where it happens. 

> How do I find out which keys can be set?

They keys that can be set depend on the server. You can really set anything on the client, and the server may ignore it or interpret it in some way. I'd image setting
```
conf.HiveConfiguration = map[string]string{"livy.server.sessionId":"0"}
```

would work. [This test](https://github.com/beltran/gohive/blob/cb0d49e69d68a27c1f16f7bd217125c799de0a43/hive_test.go#L312) shows how it can be done. The key set in this case is `hadoop.madeup.one`.

**Comment by LiShangAn** [comment]
Understood, thanks :)
