### ISSUE TITLE
kerberos auth host

### ISSUE THREAD

**Issue by kerwin-wang** [beltran/gohive#171]
connect kdc and hive has the same host can be ok, but how to do when they are different

**Comment by beltran** [comment]
This should be working as well. You can check [one of the tests](https://github.com/beltran/gohive/blob/cb0d49e69d68a27c1f16f7bd217125c799de0a43/scripts/integration.sh#L89-L101) to see an example of an environment set up like this. [Here](https://github.com/beltran/gohive/blob/cb0d49e69d68a27c1f16f7bd217125c799de0a43/scripts/create_krbconf.sh#L15) is the kerberos host and [here](https://github.com/beltran/gohive/blob/cb0d49e69d68a27c1f16f7bd217125c799de0a43/scripts/integration.sh#L10) the host running Apache Hive (hs2.example.com, which is the default host running Apache Hive in [dhive](https://github.com/beltran/dhive)).

**Comment by kerwin-wang** [comment]
OK！Thank you very much for your help. I've solved this problem with refactoring this method of Connect in the file of hive.go.
e.g. func Connect(kdcHost, host string, port int, auth string,
	configuration *ConnectConfiguration) (conn *Connection, err error) {
	
}

**Comment by beltran** [comment]
Interesting, then I don't think I fully understood the original question, could you share your patch or open a pull request with the code? It could be useful for more people.

In any case I'm closing this issue since it seems fixed.

**Comment by kerwin-wang** [comment]
I am so sorry！My English is not good. I will sort out the code and send you
