### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wuzuoliang** [beltran/gohive#174]
file : hive.go
line: 538

<img width="737" alt="image" src="https://user-images.githubusercontent.com/20548879/157163423-b559c2e9-986a-4593-9677-7af5b47dbf60.png">
<img width="983" alt="image" src="https://user-images.githubusercontent.com/20548879/157163460-f467ff56-4189-4f55-9af8-dc1e2e04e90f.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/20548879/157163481-509b1a0b-dc76-4e87-a57a-e3a42444cf44.png">

when _result64.GetSuccess() return TCLIServiceExecuteStatementResult_Success_DEFAULT 
...
then convert int(*responseExecute.Status.ErrorCode) it will panic
because responseExecute.Status is nil

**Comment by beltran** [comment]
Hello, thank you for reporting this, note this is [fixed](https://github.com/beltran/gohive/blob/v1.5.2/hive.go#L540) in the [latest release](https://github.com/beltran/gohive/releases/tag/v1.5.2), so you should upgrade the version of the client to get rid of this error.
