### ISSUE TITLE
v1.5.3 compile error

### ISSUE THREAD

**Issue by SennoYuki** [beltran/gohive#178]
Build error when using v1.5.3 . It seems there is a bug. The below is build output
`# github.com/beltran/gohive
../../go/pkg/mod/github.com/beltran/gohive@v1.5.3/hive.go:210:18: assignment mismatch: 2 variables but thrift.NewTSSLSocketConf returns 1 value
../../go/pkg/mod/github.com/beltran/gohive@v1.5.3/hive.go:216:18: assignment mismatch: 2 variables but thrift.NewTSocketConf returns 1 value`

**Comment by beltran** [comment]
Hello, what thrift version are you using?

**Comment by SennoYuki** [comment]
> Hello, what thrift version are you using?

Oh, It should be the wrong thrift version used in my project go mod file. Thanks!
