### ISSUE TITLE
please answer，thank you

### ISSUE THREAD

**Issue by hankkhan** [beltran/gohive#179]
Hello author, now we have a problem, that kinit has been successful, gohive.NewConnectConfiguration() ，the configuration.Principal = "abc" or configuration.Principal = "xyz"  will connect to hive successfully no matter what value is set, why is this? Please help to answer thank you

**Comment by beltran** [comment]
Hello, the field [Principal](https://github.com/beltran/gohive/blob/37213802c234c974eea59445d57df20f919bdf2f/hive.go#L51) is not read anywhere, so it doesn't matter what you set it to. I guess I added it at some point and then forgot to use it. You should probably ignore it as well and leave it unset.

**Comment by hankkhan** [comment]
Dear author, now we still encounter a problem, kdc and hive are on different server nodes, kinit has been successful, but when connecting to hive, Bad SASL negotiation status: 3 (GSS initiate failed) will occur. What is the general reason for this? ? please help thanks

**Comment by beltran** [comment]
These errors are hard to debug, either gohive, Hive or the KDC server is misconfigured. You can try to connect with other clients, and if you can, you'd know gohive is misconfigured, if you can't, then it's the Hive or the KDC server
