### ISSUE TITLE
Exec PENDING_STATE 

### ISSUE THREAD

**Issue by app910** [beltran/gohive#185]
execute sql : cursor.Exec(ctx, "select id from  users limit 10")

log error:gohive: operation in state (PENDING_STATE) without task status or error message

![1](https://user-images.githubusercontent.com/51191654/165035954-36fb0b11-f63f-4866-8ad4-5962b8c6f978.png)

**Comment by beltran** [comment]
Looks like a bug indeed and that looks like the correct fix, would you mind opening a pull request?

**Comment by beltran** [comment]
Thanks for reporting, I've added the fix
