### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by wanghao0123** [beltran/gohive#186]
hi，there is some error
![image](https://user-images.githubusercontent.com/30911503/167324975-f0aa53f3-57dd-4325-b493-172fbadd5a0a.png)
![image](https://user-images.githubusercontent.com/30911503/167325359-15c054c3-3a47-444a-b12f-dc51d8a416a2.png)
![image](https://user-images.githubusercontent.com/30911503/167325392-3ad23128-94c9-4b3f-b222-cee46d4ce559.png)
![image](https://user-images.githubusercontent.com/30911503/167325411-7fe30239-29b7-47fd-bc92-a335870ba40f.png)

**Comment by beltran** [comment]
Hello, this is happening because you're building against a different thrift version than [v0.14.1](https://github.com/beltran/gohive/blob/master/go.mod#L6).
