### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wuzuoliang** [beltran/gohive#192]
tag: 1.5.2

panic: runtime error: invalid memory address or nil pointer dereference

github.com/beltran/gohive.(Cursor).executeAsync(0xc00ac1a000, {0x1d63090, 0xc000084078}, {0xc0014c49c0, 0xc1})
   /var/lib/jenkins/go/pkg/mod/github.com/beltran/gohive@v1.5.2/hive.go:541 +0x324
github.com/beltran/gohive.(Cursor).Execute(0xc00ac1a000, {0x1d63090, 0xc000084078}, {0xc0014c49c0, 0x3d89}, 0x0)
   /var/lib/jenkins/go/pkg/mod/github.com/beltran/gohive@v1.5.2/hive.go:466 +0x39
   
  
responseExecute.GetStatus().ErrorCode is nil 

<img width="905" alt="image" src="https://user-images.githubusercontent.com/20548879/174533758-ad36812b-2e24-4ab4-aa7e-15cce99875b0.png">

**Comment by beltran** [comment]
Thank you for reporting this
