### ISSUE TITLE
How to solve "Incorrect FrameSize"?

### ISSUE THREAD

**Issue by vista2001** [beltran/gohive#193]
While I use the code `cursor.hasMore()`,I found that when the content size returned from database  more than 16M, the cursor will raise an exception ,the errMsg says that " Incorrect FrameSize(16939702)".
I think the exception can be fix by change the MaxFrameSize of thrift,but how can I do this?

**Comment by beltran** [comment]
Hello, do you have the whole stacktrace? What transport are you using? And what auth mechanism? In any case this will most likely get fixed by setting a higher number [here](https://github.com/beltran/gohive/blob/c7102aa35cfcc79c1665f98b7bacc6432ade4686/sasl_transport.go#L23). At the moment this is not configurable so new code must be added.

**Comment by beltran** [comment]
Let me know if the added code doesn't work for you to fix this issue. You should be able to do `configuration.MaxSize = SOME_HIGH_NUMBER`

**Comment by vista2001** [comment]
Thanks for your work. I will up the full trackstack and test results soon

**Comment by vista2001** [comment]
My trackstacks:
`err:error(*github.com/apache/thrift/lib/go/thrift.tTransportException) *{typeId: 0, err: error(*errors.errorString) *{s: "Incorrect frame size (16939748)"}, msg: "Incorrect frame size (16939748)"}
	data:*github.com/apache/thrift/lib/go/thrift.tTransportException {typeId: 0, err: error(*errors.errorString) *{s: "Incorrect frame size (16939748)"}, msg: "Incorrect frame size (16939748)"}
	    :github.com/apache/thrift/lib/go/thrift.tTransportException {typeId: 0, err: error(*errors.errorString) *{s: "Incorrect frame size (16939748)"}, msg: "Incorrect frame size (16939748)"}
	    typeId:0
	    err:*errors.errorString {s: "Incorrect frame size (16939748)"}
	    	data:*errors.errorString {s: "Incorrect frame size (16939748)"}
	    	    :errors.errorString {s: "Incorrect frame size (16939748)"}
	    	    	s:"Incorrect frame size (16939748)"
		msg:"Incorrect frame size (16939748)"`
My connection info:
`conn:
auth:"NONE"
transport:
mechainism:"PLAIN"
maxLength:16384000 = 0xfa0000`
The  param `configuration.MaxSize = SOME_HIGH_NUMBER` took the effect, after I uesed the param , the `cursor.hasMore()` got the correct data.
Thanks for your work!

**Comment by beltran** [comment]
Happy to hear, thank you for following up!
