### ISSUE TITLE
Incorrect frame size 

### ISSUE THREAD

**Issue by shencw** [beltran/gohive#200]
an error occurs when I use the same connection and request data using different cursors at the same time

What should I do in this situation？

**Comment by beltran** [comment]
What error are you getting? I'm not surprised this is not working. There should be one cursor per connection. Why not just have this?

**Comment by shencw** [comment]
> 你遇到了什么错误？我并不惊讶这不起作用。每个连接应该有一个游标。为什么不只拥有这个？

I wrote a timed task and I want multiple processes to synchronize data at the same time, but it is the same connection. Do I need to re-establish the connection?

**Comment by beltran** [comment]
Yes, you need one cursor per connection. I've actually never tried to use several cursors on the same connection.   It's possible it works, or that it doesn't work but there's an easy fix. But the library was built with the assumption there would be one cursor per connection.

**Comment by shencw** [comment]
> 是的，每个连接需要一个光标。我实际上从未尝试在同一连接上使用多个游标。它可能有效，或者它不起作用，但有一个简单的解决方法。但是该库是在假设每个连接有一个游标的情况下构建的。

thx, is there a recommended way to create a connection pool ?

**Comment by beltran** [comment]
> is there a recommended way to create a connection pool ?

Unfortunately I'm not aware of any best practices, but if you end up doing this please share the knowledge you acquire 🙂

**Comment by shencw** [comment]
> > is there a recommended way to create a connection pool ?
> 
> Unfortunately I'm not aware of any best practices, but if you end up doing this please share the knowledge you acquire 🙂

thx ~
