### ISSUE TITLE
ConnectZookeeper panic

### ISSUE THREAD

**Issue by danieldiasptc** [beltran/gohive#202]
Hey,

I'm trying to connect to hive using the `ConnectZookeeper` method, but I'm facing a panic with the error. `zk: node does not exist`

My suggestions is to instead of raisin a panic, would be better to just return the error, and let the user handle it?

Here: https://github.com/beltran/gohive/blob/master/hive.go#L112

Also, is this error strictly server side related? I'm having an hard time debugging why is this error happening

**Comment by beltran** [comment]
Thanks for the suggestion.

I'm not sure if the error is always server related, hopefully this can be seen now from the error message.
