### ISSUE TITLE
use in hive 1.1.0  fetch data uncompleted

### ISSUE THREAD

**Issue by fengwangjie** [beltran/gohive#206]
<img width="925" alt="image" src="https://user-images.githubusercontent.com/8510914/216258642-df5c3c0b-7f01-42d6-98a8-1e7e6ac8479b.png">
same sql, cli query 21 rows use gohive in go program feach 0 rows

`cursor := connection.Cursor()
	cursor.Exec(ctx, "select n1,systime from tt_8103z where systime >='2022-12-15 11:00:01' and systime <= '2022-12-15 11:00:22'")
	if cursor.Err != nil {
		log.Fatal(cursor.Err)
	}
	// descMap := make(map[string]string)
	var s string
	var s1 string
	for cursor.HasMore(ctx) {
		// m := cursor.RowMap(ctx)
		cursor.FetchOne(ctx, &s, &s1)
		log.Println(s, s1)
		// print(m)
		// log.Println(descMap)
	}
`
![image](https://user-images.githubusercontent.com/8510914/216259618-aef46285-3d89-40b2-94af-e8297af1aa61.png)

**Comment by fengwangjie** [comment]
i find this issue not go hive client , actual hive cli diff hiveserver2

**Comment by joint-song** [comment]
I think your dependent jars of hs2 and Hive CLI have the different versions(hive-exec/hive-comon etc.). They may have different behaviors even with the same sql.
