### ISSUE TITLE
hive-site.xml location

### ISSUE THREAD

**Issue by yosychenko** [beltran/gohive#207]
Hi @beltran! 

I don't really understand, where should I put `hive-site.xml` file in order to use it to connect to Hive via `gohive`? How do I set a custom path to this file? Do I need to define env variable containing path to this file?

I see, that it has been mentioned in [docs](https://github.com/beltran/gohive#connect-with-sasl-kerberos), but I can't find any mentions of this file in `gohive` code. Can you please point out where this file is loaded and parsed in `gohive`? Thanks!

**Comment by beltran** [comment]
hive-site.xml is not parsed by gohive. As far as I know it's only read by the server. [Here](https://github.com/beltran/gohive/blob/8f113739dd9d2671d56ae3181ce693d5b12d74b4/hive_test.go#L313-L315) there's an example of how to set properties from gohive.
