### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by guichenglin** [beltran/gohive#208]
panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a2a4a]
	
	goroutine 1 [running]:
	github.com/beltran/gohive/hiveserver.(*TRowSet).GetColumns(...)
		/data/ba-build/vendor/github.com/beltran/gohive/hiveserver/HiveServer.go:5977
	github.com/beltran/gohive.(*Cursor).FetchLogs(0xc0002b2100, 0xa80238, 0xc0002a2240, 0xc0002ce000)
		/data/ba-build/vendor/github.com/beltran/gohive/hive.go:588 +0xca
	github.com/beltran/gohive.(*Cursor).Execute(0xc0002b2100, 0xa80238, 0xc0002a2240, 0xc0002ce000, 0xc1, 0x0)
		/data/ba-build/vendor/github.com/beltran/gohive/hive.go:488 +0x193
	github.com/beltran/gohive.(*Cursor).Exec(...)
		/data/ba-build/vendor/github.com/beltran/gohive/hive.go:461
	hiveToDB/apps.(*hiveToDB).Run(0xc0001f1d28, 0x7ffdbe4af506, 0x66, 0xc00020e0f0)
		/data/ba-build/apps/hive2db.go:192 +0x1266
	main.main.func1(0xc0000b88c0, 0x0, 0xa)
		/data/ba-build/main.go:75 +0x565
	github.com/urfave/cli/v2.(*App).RunContext(0xc0000dd520, 0xa80270, 0xc0000d4010, 0xc0000da000, 0x2d, 0x30, 0x0, 0x0)
		/data/ba-build/vendor/github.com/urfave/cli/v2/app.go:322 +0x6fe
	github.com/urfave/cli/v2.(*App).Run(...)
		/data/ba-build/vendor/github.com/urfave/cli/v2/app.go:224
	main.main()
		/data/ba-build/main.go:79 +0x2f1

**Comment by beltran** [comment]
Thank you for reporting the issue
