### ISSUE TITLE
Assignment Mismatch | Thrift

### ISSUE THREAD

**Issue by pawanmsr** [beltran/gohive#211]
Occurred during:
1. Go Mod Update `go get -u ./...`
2. Package Build `go build -o bin/package cmd/main.go`

```sh
# github.com/beltran/gohive
../../go/pkg/mod/github.com/beltran/gohive@v1.5.4/hive.go:216:18: assignment mismatch: 2 variables but thrift.NewTSSLSocketConf returns 1 value
../../go/pkg/mod/github.com/beltran/gohive@v1.5.4/hive.go:222:18: assignment mismatch: 2 variables but thrift.NewTSocketConf returns 1 value
```

**Comment by pawanmsr** [comment]
**[NewTSSLSocketConf](https://github.com/apache/thrift/blob/master/lib/go/thrift/ssl_socket.go#L53)** in thrift returns just one value. In [hive.go](https://github.com/beltran/gohive/blob/master/hive.go#L216), it is expecting an error value as well.

They are both old changes. Shall I raise a PR to fix them?

**Comment by pawanmsr** [comment]
GoHive uses thrift v0.14.1. The latest is v0.18.1. Is it possible to upgrade Gohive?

**Comment by beltran** [comment]
I would accept this change, but you'll need to run scrips/generate_thrift.sh. I'm not sure how well this is going to work.

**Comment by beltran** [comment]
This should be fixed now with the latest commit, let me know if it's still an issue.
