### ISSUE TITLE
how to specify mote than one host

### ISSUE THREAD

**Issue by Antirecord** [beltran/gohive#220]
Good afternoon I have 3 hiveserver2 hosts:

  abc-def-31-04.host.com:10000,abc-def-31-05.host.com:10000,abc-def-31-06.host.com:10000

how do i insert them into gohive.connect("here", 10000, etc ) ?

I get an error if I enter one host there:

""Failed to open new session: java.lang.RuntimeException: java.net.ConnectException: Call From abc-def-31-05.host.com/{ip} to abc-def-31-05.host.com:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused""

Tell me what could be the problem

**Comment by beltran** [comment]
Hello, connections to multiple hosts is not supported. You can only insert a single host in `"here"`:

` gohive.connect("abc-def-31-04.host.com", 10000, etc )`
