### ISSUE TITLE
support go version problem？

### ISSUE THREAD

**Issue by DunZane** [beltran/gohive#246]
if i am using go 1.17, what best version of gohive for me?

**Comment by beltran** [comment]
Hello, only certain go versions are tested because there are not that many
Travis CI credits available, and the project runs out of them fairly
quickly. However the behavior should be the same with all the go versions.
I'd recommend the latest release.

**Comment by DunZane** [comment]
i have used v1.5.4. did't got any problem right now

**Comment by beltran** [comment]
Thank you for reporting back
