### ISSUE TITLE
go get issue 

### ISSUE THREAD

**Issue by arjun-ajith-gl** [beltran/gohive#33]
Getting the following error when doing `go get github.com/beltran/gohive`

`# github.com/beltran/gohive/vendor/github.com/beltran/gssapi
../../beltran/gohive/vendor/github.com/beltran/gssapi/buffer.go:9:10: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by beltran** [comment]
@arjun-ajith-gl sorry for the late reply. You're missing the krb5 kerberos libraries. In ubuntu they can be installed with `apt-get install libkrb5-dev`.

**Comment by beltran** [comment]
After the latest commit in master you should be able to install it with just:
`go get github.com/beltran/gohive`. If you want to use kerberos, install the krb5 libraries and: `go get -tags kerberos github.com/beltran/gohive`
