### ISSUE TITLE
Bad SASL negotiation status: 3 (GSS initiate failed)

### ISSUE THREAD

**Issue by wangbokun** [beltran/gohive#45]
configuration := gohive.NewConnectConfiguration()
        configuration.Service = "hive"
        configuration.FetchSize = 1000
 
connection, errConn := gohive.Connect("xx.xx.xx.xx", 10000, "KERBEROS", configuration)
        llog.Debug("--------",errConn)

kinit have done: kinit -kt ./secret.keytab hive/hs2.example.com@EXAMPLE.COM
return err info:
019/02/23 23:14:17 Bad SASL negotiation status: 3 (GSS initiate failed)

**Comment by beltran** [comment]
Could be several things but probably something is set wrong in kerberos.

Maybe this could be fixed setting the environment variable KRB5CCNAME like [here](https://github.com/beltran/gohive/blob/master/hive_test.go#L1165). You can check [how it's set up in tests](https://github.com/beltran/gohive/blob/master/scripts/integration.sh#L71).

Could be as well there's something wrong with your /etc/krb5.conf file. [This is a sample one](https://github.com/beltran/gohive/blob/master/scripts/create_krbconf.sh#L5) that works for the tests.
