### ISSUE TITLE
go connect to hive with NOSASL mode

### ISSUE THREAD

**Issue by yy8623977** [beltran/gohive#46]
# go connect to hive with NOSASL mode
here is my description on my hive: i can connect to my hive without username and password in normal, the setting hive.server2.authentication in hive-site.xml is NOSASL

a error Socket already connected appeared when I used go connect to hive, below is my main.go

hope you give me some advice after you view this issue, thanks

```
package main

import (
	"context"
	"log"

	"github.com/beltran/gohive"
)

func main() {
	async := false
	ctx := context.Background()
	configuration := gohive.NewConnectConfiguration()
	// is this a database?
	configuration.Service = "bulut"
	configuration.FetchSize = 1000

	connection, errConn := gohive.Connect("10.125.0.15", 10000, "NOSASL", configuration)
	if errConn != nil {
               // the error Socket already connected was occured here
		log.Fatal(errConn)
	}
	cursor := connection.Cursor()


	cursor.Execute(ctx, "SELECT * FROM goTest", async)
	if cursor.Err != nil {
		log.Fatal(cursor.Err)
	}

	var users []User
	for cursor.HasMore(ctx) {
		var user User
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		cursor.FetchOne(ctx, &user.Id, &user.Name)
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		users = append(users,user)
	}
	log.Println(users)

	cursor.Close()
	connection.Close()
}

type User struct {

	Id int
	Name string

}
```

**Comment by beltran** [comment]
Definitely you shouldn't be setting `configuration.Service = "bulut"`. Thay may allow to connect if hive is configured correctly. Which should happen if `hive.server2.authentication = NOSASL`. If that doesn't work it will help if you can provide the exception that happens in hive when you try to connect and fail (not the the error in the driver, but the hive exception).
