### ISSUE TITLE
NULL values

### ISSUE THREAD

**Issue by BogdanovDenis** [beltran/gohive#47]
How to get nil field value, not default?

**Comment by beltran** [comment]
I'm not sure I understand, what happens when you select a column with a null value, I guess nil is set for that field.

**Comment by BogdanovDenis** [comment]
for example:
```
var i int32
	for cursor.HasMore(ctx) {
		cursor.FetchOne(ctx, &i)
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		log.Println(i)
	}
```

If in this case we have a NULL in hive, we get 0 in the variable` i`. But if we have 0 in the hive, then the variable `i` will also have 0. 
As a result, we can not understand what was in the database.

if I will do as follows:
```
var i *int64
	for cursor.HasMore(ctx) {
		cursor.FetchOne(ctx, i)
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		log.Println(i)
	}
```
i will get the following:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b6912]

goroutine 1 [running]:
github.com/beltran/gohive.(*Cursor).FetchOne(0xc000122400, 0x17049a0, 0xc0000a8000, 0xc000157f68, 0x1, 0x1)
	/Users/projects/go/src/github.com/beltran/gohive/hive.go:544 +0x9c2
```

In the standard library we have sql.NullInt64 or we can use pointers as in the example above.

How can i get nil using your library?

**Comment by beltran** [comment]
Thank you for pointing this out to me. You couldn't before but you should be able now with the latest commit. [This](https://github.com/beltran/gohive/blob/master/hive_test.go#L531) is how you would do it with `RowMap` interface and [this](https://github.com/beltran/gohive/blob/master/hive_test.go#L1200) with the `FetchOne` interface. Let me know if you try it and bump into anything.

**Comment by BogdanovDenis** [comment]
Ok, thanks for the changes, but could you test with the function `cursor.HasMore(ctx)`?
Because I have several problems that arise when using this function, but when I don't use it, everything is fine.

for example:
```
for cursor.HasMore(ctx) {
		var i1 =new(int64)
		var i2 =new(int64)
		cursor.FetchOne(context.Background(), &i1, &i2)
		if cursor.Err != nil {
			log.Fatal(cursor.Err)
		}
		fmt.Println(i1, i2)
	}
```
prints the following:
```
<nil> 0xc0000a6150
<nil> 0xc0000a6160
<nil> 0xc0000a6170
<nil> 0xc0000a6180
<nil> 0xc0000a6190
<nil> 0xc0000a61a0
<nil> 0xc0000a61b0
<nil> 0xc0000a61c0
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/beltran/gohive.isNull(...)
	/Users/projects/go/src/github.com/beltran/gohive/hive.go:713
github.com/beltran/gohive.(*Cursor).FetchOne(0xc000194000, 0x17062e0, 0xc0000b6000, 0xc000151f58, 0x2, 0x2)
	/Users/projects/go/src/github.com/beltran/gohive/hive.go:643 +0x1ad4
```
or am i doing something wrong?

**Comment by beltran** [comment]
Thank you for checking this, fixed the bug. Should be fine now.
