### ISSUE TITLE
gohive under CentOS Linux release 7.5

### ISSUE THREAD

**Issue by Chenhb123** [beltran/gohive#61]
Hi,
Can I connect the hive with kerberos authentication under **_centos7_** by the following operation?
yum install -y krb5-devel
go get -tags kerberos github.com/beltran/gohive
Thanks!

**Comment by beltran** [comment]
Hello, I'm afraid I can't help you. I haven't tested it nor do I have a way to test it. I don't know if the command `yum install -y krb5-devel` is the right one, but as long as the GSSAPI C library is installed you should be able to later install gohive with `go get -tags kerberos github.com/beltran/gohive`.
