### ISSUE TITLE
Create new tag please!!!

### ISSUE THREAD

**Issue by rssh-jp** [beltran/gohive#80]
Hi beltran,
I use beltra/gohive heavy, and I use go module.
Now if I execute `go mod init`
```
go 1.13

require github.com/beltran/gohive v1.0.0
```

This version `v1.0.0` has connection failure.
https://github.com/beltran/gohive/blob/v1.0.0/hive.go#L166

Please create new tag and make me happy!!

Thanks!!

**Comment by rssh-jp** [comment]
I did this to solve

``` go.mod
go 1.13

require github.com/beltran/gohive 075073
```

**Comment by beltran** [comment]
Thank you for using the driver! I've created v1.0.1: https://github.com/beltran/gohive/releases

**Comment by rssh-jp** [comment]
Thenk you!
I'm happy!
