### ISSUE TITLE
RowMap do not map to all column in output

### ISSUE THREAD

**Issue by athiyutbest** [beltran/gohive#84]
i have an issue when i use "m := cursor.RowMap(context.Background())" for the query like "select a,b,c from tableName"(data type: a int32,b string,c string).I only receive the data from column a, but when i use "cursor.FetchOne(ctx, &a, &b, &c)" i recevie the data for all column

**Comment by beltran** [comment]
Hello, thank you for reporting this. I have been unable to reproduce it. Could you paste the output of the table description: `describe extended tableName;`, also do you have the data of the rows this is happening with?
