### ISSUE TITLE
Invalid method name: 'OpenSession'

### ISSUE THREAD

**Issue by yjhmelody** [beltran/gohive#92]
I try to run the demo in `NOSASL`, but get the following error. How to resolve it ?

```
Invalid method name: 'OpenSession'
```

**Comment by beltran** [comment]
Hello, I've never seen it and this kind of connection it's working as expected, is that the complete error message? What the environment it's being ran and the OS?

**Comment by yjhmelody** [comment]
I run it in macos 10.15.3.
It's complete error message.

**Comment by beltran** [comment]
This would be the error I expect to see if you were connecting to a non hive server. I believe it's complaining that the server doesn't have the `OpenSession` method which should be present on hive. What version of hive are you running?

**Comment by yjhmelody** [comment]
@beltran You are right, it's my fault that I connected to a wrong ip.
